bibliotekon/user/__init__.py
# -*- coding: utf-8 -*-

# This file is part of Bibliotekon.
#
# Copyright (c) 2013 Román Ginés Martínez Ferrández <rgmf@riseup.net>
#
# Bibliotekon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Bibliotekon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar. If not, see <http://www.gnu.org/licenses/>.

from bibliotekon import app
from bibliotekon.db.database import db_session

@app.teardown_appcontext
def shutdown_session(exception=None):
    db_session.remove()

bibliotekon/user/views.py
# -*- coding: utf-8 -*-

# This file is part of Bibliotekon.
#
# Copyright (c) 2013 Román Ginés Martínez Ferrández <rgmf@riseup.net>
#
# Bibliotekon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Bibliotekon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar. If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, session, render_template, request, flash
from flask.ext.babel import gettext

from sqlalchemy.exc import SQLAlchemyError

from bibliotekon import app
from bibliotekon.auth.models import CoreUser
from bibliotekon.auth.lib import login_required
from bibliotekon.auth.forms import RegistrationForm
from bibliotekon.auth.tools import update_user
from bibliotekon.db.database import db_session


mod = Blueprint('user', __name__, template_folder = 'templates')


@mod.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    """The user home.
    
    Show the user information.
    """
    user = CoreUser.query.get(session['user_id'])
    return render_template('home.html', user=user)


@mod.route('/update', methods=['GET', 'POST'])
def update():
    """The user update information view.

    Update the user information.
    """
    form = RegistrationForm()
    user = CoreUser.query.get(session['user_id'])
    if request.method == 'POST' and form.validate():
        try:
            user.name = form.name.data if form.name.data else ''
            user.surname = form.lname.data if form.lname.data else ''
            user.email = form.email.data if form.email.data else ''
            user.username = form.username.data if form.username.data else ''
            if form.passwd.data or form.passwdrepeat.data:
                user.passwd = form.passwd.data                
            update_user(user, form)
            flash(gettext('The profile have been updated.'), 'success')
        except SQLAlchemyError, e:
            flash(gettext('There have been a database error.'), 'error')
            app.logger.error('There have been a database error: %s' % e)
            db_session.rollback()
        except Exception, e:
            flash(gettext('There have been a weird error.'), 'error')
            app.logger.error('There have been a weird error: %s' % e)
            db_session.rollback()

    return render_template('update.html', user=user, form=form)

bibliotekon/user/templates/home.html
{#
# This file is part of Bibliotekon.
#
# Copyright (c) 2013 Román Ginés Martínez Ferrández <rgmf@riseup.net>
#
# Bibliotekon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Bibliotekon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar. If not, see <http://www.gnu.org/licenses/>.
#}

{% extends "layout.html" %}

{% block content %}
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4 offset4">
      <h2>{{ _('My profile') }}</h2>

      <div class="item">
        <p class="mylead">
          <strong>{{ _('Name') }}:</strong> {{ user.name if user.name else '' }}
        </p>
        <p class="mylead">
          <strong>{{ _('Last name') }}:</strong> {{ user.surname if user.surname else '' }}
        </p>
        <p class="mylead">
          <strong>{{ _('Username') }}:</strong> {{ user.username if user.username else '' }}
        </p>
        <p class="mylead">
          <strong>{{ _('E-mail') }}:</strong> {{ user.email if user.email else '' }}
        </p>
        <ul class="nav nav-pills">
          <li>
            <a href="{{ url_for('user.update') }}">{{ _('Change') }}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bibliotekon/user/templates/update.html
{#
# This file is part of Bibliotekon.
#
# Copyright (c) 2013 Román Ginés Martínez Ferrández <rgmf@riseup.net>
#
# Bibliotekon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Bibliotekon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar. If not, see <http://www.gnu.org/licenses/>.
#}

{% extends "layout.html" %}

{% block content %}
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4 offset4">

      {% from "forms/macros.html" import with_errors %}
      {% from "forms/macros.html" import flash_messages %}

      {{ with_errors(form.name) }}
      {{ with_errors(form.lname) }}
      {{ with_errors(form.username) }}
      {{ with_errors(form.email) }}
      {{ with_errors(form.passwd) }}
      {{ with_errors(form.passwdrepeat) }}
      {{ flash_messages(get_flashed_messages(with_categories=True)) }}


      <h2>{{ _('My profile') }}</h2>

      <form method="POST" action="" class="form-horizontal form-signin">
        {{ form.csrf_token }}

        {{ form.name(class="input-block-level", placeholder=_("Name"),
                     value=user.name if user.name else '') }}
        {{ form.lname(class="input-block-level", placeholder=_("Last Name"),
                      value=user.surname if user.surname else '') }}
        {{ form.username(class="input-block-level", placeholder=_("Username"),
                         value=user.username if user.username else '') }}
        {{ form.email(class="input-block-level", placeholder=_("E-mail"),
                      value=user.email if user.email else '') }}
        {{ form.passwd(class="input-block-level", placeholder=_("Password")) }}
        {{ form.passwdrepeat(class="input-block-level", placeholder=_("Repeat password")) }}
       <button id="cancel-btn" class="btn btn-large" type="button"
               data-href="{{ url_for('user.home') }}">
          {{ _('Cancel') }}
        </button>
        <button type="submit" class="btn btn-large">
          {{ _('Ok') }}
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
/*
@licstart  The following is the entire license notice for the 
JavaScript code in this page.

Copyright (C) 2013 Román Ginés Martínez Ferrández <rgmf@riseup.net>

The JavaScript code in this page is free software: you can
redistribute it and/or modify it under the terms of the GNU
General Public License (GNU GPL) as published by the Free Software
Foundation, either version 3 of the License, or (at your option)
any later version.  The code is distributed WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.

As additional permission under GNU GPL version 3 section 7, you
may distribute non-source (e.g., minimized or compacted) forms of
that code without the copy of the GNU GPL normally required by
section 4, provided you include this license notice and a URL
through which recipients can access the Corresponding Source.

@licend  The above is the entire license notice
for the JavaScript code in this page.
*/
</script>
<script>
$(document).ready(function(){
  $('#name').focus();

  $('#cancel-btn').on('click', function(){
    document.location.href = $(this).data('href');
  });
});
</script>
{% endblock %}